version: '3.8'


services:
  redis:
    image: 'redis:latest'
    container_name: 'spring-crawler-redis'
    ports:
      - '6379:6379'

  database:
    image: 'postgres:latest'
    container_name: 'spring-crawler-database'
    environment:
      - 'POSTGRES_DB=spring-crawler'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
