version: '3.8'


services:
  database:
    image: 'postgres:latest'
    container_name: 'spring-crawler-database'
    environment:
      - 'POSTGRES_DB=spring-crawler'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
